import type { LucideIcon } from "lucide-react";
import {
  Mail,
  Calendar,
  MessageSquare,
  FileText,
  BarChart3,
  Music,
  Camera,
  ShoppingCart,
  Cloud,
  Code2,
  Kanban,
  Wallet,
  Video,
  Map,
  Bot,
  Headphones,
  ScanFace,
  WandSparkles,
} from "lucide-react";

export type AppCategory = "Work" | "Creative" | "Communication" | "Utilities";

export interface AppLink {
  id: string;
  name: string;
  description: string;
  url: string;
  icon: LucideIcon;
  category: AppCategory;
  accent: string;
  featured?: boolean;
}

export const categories: AppCategory[] = [
  "Work",
  "Creative",
  "Communication",
  "Utilities",
];

export const apps: AppLink[] = [
  {
    id: "movies",
    name: "Jellyfin",
    description: "Watch our movie collection",
    url: "https://jellyfin.ciasullomedia.com",
    icon: Video,
    category: "Creative",
    accent: "300",
    featured: true,
  },
  {
    id: "shokofin",
    name: "Shokofin",
    description: "Anime collection management",
    url: "https://shoko.ciasullomedia.com",
    icon: ScanFace,
    category: "Work",
    accent: "220",
  },
  {
    id: "grafana",
    name: "Grafana",
    description: "Analytics and monitoring dashboards",
    url: "https://grafana.ciasullomedia.com",
    icon: BarChart3,
    category: "Work",
    accent: "162",
  },
  {
    id: "crowdsec",
    name: "CrowdSec",
    description: "Security and threat detection",
    url: "https://crowdsec.ciasullomedia.com",
    icon: Bot,
    category: "Work",
    accent: "55",
  },
    {
    id: "wizarr",
    name: "Wizarr",
    description: "User management and authentication",
    url: "https://wizarr.ciasullomedia.com",
    icon: WandSparkles,
    category: "Work",
    accent: "15",
  },
  // {
  //   id: "mail",
  //   name: "Mailbox",
  //   description: "Inbox, drafts and smart replies",
  //   url: "https://mail.google.com",
  //   icon: Mail,
  //   category: "Communication",
  //   accent: "162",
  //   featured: true,
  // },
  // {
  //   id: "calendar",
  //   name: "Calendar",
  //   description: "Schedule and manage events",
  //   url: "https://calendar.google.com",
  //   icon: Calendar,
  //   category: "Work",
  //   accent: "220",
  // },
  // {
  //   id: "chat",
  //   name: "Family Chat",
  //   description: "Channels and direct messages",
  //   url: "https://discord.com",
  //   icon: MessageSquare,
  //   category: "Communication",
  //   accent: "300",
  //   featured: true,
  // },
  // {
  //   id: "docs",
  //   name: "Documents",
  //   description: "Write, edit and collaborate",
  //   url: "https://docs.google.com",
  //   icon: FileText,
  //   category: "Work",
  //   accent: "55",
  // },
  // {
  //   id: "analytics",
  //   name: "Analytics",
  //   description: "Dashboards and live metrics",
  //   url: "https://vercel.com/analytics",
  //   icon: BarChart3,
  //   category: "Work",
  //   accent: "162",
  //   featured: true,
  // },
  // {
  //   id: "music",
  //   name: "Music",
  //   description: "Playlists and focus sounds",
  //   url: "https://open.spotify.com",
  //   icon: Music,
  //   category: "Creative",
  //   accent: "162",
  // },
  // {
  //   id: "photos",
  //   name: "Photos",
  //   description: "Gallery and quick edits",
  //   url: "https://photos.google.com",
  //   icon: Camera,
  //   category: "Creative",
  //   accent: "15",
  // },
  // {
  //   id: "store",
  //   name: "Storefront",
  //   description: "Orders, products and payouts",
  //   url: "https://shopify.com",
  //   icon: ShoppingCart,
  //   category: "Work",
  //   accent: "300",
  // },
  // {
  //   id: "cloud",
  //   name: "Cloud Drive",
  //   description: "Files, backups and sharing",
  //   url: "https://drive.google.com",
  //   icon: Cloud,
  //   category: "Utilities",
  //   accent: "220",
  // },
  // {
  //   id: "code",
  //   name: "Code Studio",
  //   description: "Repos, builds and deploys",
  //   url: "https://github.com",
  //   icon: Code2,
  //   category: "Work",
  //   accent: "162",
  // },
  // {
  //   id: "board",
  //   name: "Task Board",
  //   description: "Kanban and sprint planning",
  //   url: "https://linear.app",
  //   icon: Kanban,
  //   category: "Work",
  //   accent: "300",
  // },
  // {
  //   id: "wallet",
  //   name: "Wallet",
  //   description: "Balances and transactions",
  //   url: "https://stripe.com",
  //   icon: Wallet,
  //   category: "Utilities",
  //   accent: "162",
  // },
  // {
  //   id: "video",
  //   name: "Video Calls",
  //   description: "Meetings and screen share",
  //   url: "https://meet.google.com",
  //   icon: Video,
  //   category: "Communication",
  //   accent: "220",
  // },
  // {
  //   id: "maps",
  //   name: "Maps",
  //   description: "Navigation and places",
  //   url: "https://maps.google.com",
  //   icon: Map,
  //   category: "Utilities",
  //   accent: "55",
  // },
  // {
  //   id: "assistant",
  //   name: "AI Assistant",
  //   description: "Chat, draft and automate",
  //   url: "https://v0.app",
  //   icon: Bot,
  //   category: "Creative",
  //   accent: "162",
  //   featured: true,
  // },
  // {
  //   id: "support",
  //   name: "Support Desk",
  //   description: "Tickets and help center",
  //   url: "https://vercel.com/help",
  //   icon: Headphones,
  //   category: "Communication",
  //   accent: "15",
  // },
];
